### ISSUE TITLE
JUnit5 tests are no longer executed by maven :(

### ISSUE THREAD

**Issue by Andrei94** [stevenschwenke/WritingAwesomeJavaCodeWorkshop#30]
https://github.com/junit-team/junit5/issues/1494

**Comment by Andrei94** [comment]
**Solution:**
* use `junit-jupiter-engine` instead of `junit-jupiter-api`
* update `maven-surefire-plugin` to at least 2.**22**.1 (it doesn't work with 2.**20**.1)
* add the following configuration for the plugin:
```
<configuration>
   <includes>
     <include>*</include>
   </includes>
</configuration>
```

Unfortunately now the build will fail because there are already broken tests 😅

**Comment by stevenschwenke** [comment]
Everything fine now - thank you very much for creating this issue!
